# 0. Модель данных

* **разница между mutable и immutable;**

In [1]:
test_t = (1,2,3)
test_t[0] = 100

TypeError: 'tuple' object does not support item assignment

In [2]:
test_l = [1,2,3]
test_l[0] = 100

String mutable?

* **за динамическую структуру придется платить памятью, за создание новых статических - быстродействием ;**

In [3]:
def test_1(size):
    test = list()
    for i in xrange(size):
        test.append(i)

In [4]:
%timeit test_1(10000)

1000 loops, best of 3: 810 µs per loop


In [5]:
def test_2(size):
    test = ()
    for i in xrange(size):
        test + (i,)

In [6]:
%timeit test_2(10000)

1000 loops, best of 3: 882 µs per loop


* **пользуйтесь оптимизированными конструкциями - comprehension, sum, xrange, map, filter**

Я стараюсь, где это возможно, пользоваться comprehension:

In [7]:
% timeit -n 100 filter(lambda x: x%2 == 0, xrange(100000))

100 loops, best of 3: 14 ms per loop


In [8]:
% timeit -n 100 [el for el in xrange(100000) if el % 2 == 0]

100 loops, best of 3: 7.2 ms per loop


* **предпочитайте итераторы явному созданию новых конструкций**

Если вы не хотите видеть 2х - 3х overhead'ы по сравнению с исходным размером задачи.

# 1. Помните о разнице между str() и unicode()

Если эта граница по-пержнему не очевидна - http://joelonsoftware.com/articles/Unicode.html .

# 2. Numpy

In [9]:
import numpy as np

Число осей в массиве - это его ранг.

Массив ранга один:

In [10]:
np.array([1,2,3], dtype=np.uint16)

array([1, 2, 3], dtype=uint16)

Массив ранга два:

In [11]:
np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]], dtype=np.uint16)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=uint16)

Массив ранга 3:

In [12]:
np.random.rand(4,4,4)

array([[[ 0.96459358,  0.53332425,  0.77194137,  0.82870008],
        [ 0.6215895 ,  0.74601024,  0.49866786,  0.28634469],
        [ 0.76221066,  0.07079474,  0.3653702 ,  0.46495461],
        [ 0.37953841,  0.95452452,  0.9477207 ,  0.64821608]],

       [[ 0.32869077,  0.44092676,  0.16224796,  0.78134798],
        [ 0.92174122,  0.47246034,  0.77027927,  0.74824274],
        [ 0.80820269,  0.74118005,  0.77890263,  0.63394891],
        [ 0.15937263,  0.77615165,  0.97483649,  0.82829814]],

       [[ 0.82858307,  0.81196669,  0.93140693,  0.15142505],
        [ 0.31703331,  0.70907463,  0.78400745,  0.82588634],
        [ 0.20579192,  0.96704415,  0.51760333,  0.55774635],
        [ 0.89540685,  0.07926291,  0.75935134,  0.39851598]],

       [[ 0.15344601,  0.39335763,  0.01522904,  0.63424851],
        [ 0.46118917,  0.99096042,  0.81152308,  0.2083623 ],
        [ 0.1557377 ,  0.87910753,  0.27093945,  0.63430266],
        [ 0.81487075,  0.30914172,  0.86772554,  0.33881118]]])

И так далее...

Любая операция типа reduce() снижает ранг массива до (n-1), где n - предыдущий ранг.

Номер оси - позиция в кортеже shape.

In [13]:
rank_two = np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]], dtype=np.uint16)

In [14]:
rank_two.shape

(3, 4)

In [15]:
np.sum(rank_two, axis=1)

array([10, 10, 10], dtype=uint64)

In [16]:
rank_three = np.random.rand(3,4,5)

In [17]:
rank_three.shape

(3, 4, 5)

In [19]:
np.sum(rank_three, axis=0).shape

(4, 5)

In [20]:
np.sum(rank_three, axis=1).shape

(3, 5)

** Помните про правила broadcasting **

Можно:

In [21]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

''';

Нельзя:

In [22]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
''';